name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: npm install
    
      - name: Restore git history
        run: git restore package-lock.json
        
      - name: Set git config
        run: |
            git config --global user.name "Batuhan Ozen"
            git config --global user.email "iletisim@batuhanozen.com"
        
      - name: Bump version and publish
        run: |
            npm run build
            npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
