# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: NPM CI

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: git config --global user.email "iletisim@batuhanozen.com"
      - run: git config --global user.name "Batuhan Ozen"
      - run: npm ci
      - run: npm run build
      - run: cd dist
      - run: ls -a
      - run: cd ..
      - run: npm publish
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
