# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: NPM CI

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Configure Git
        run: |
          git config --global user.email "iletisim@batuhanozen.com"
          git config --global user.name "Batuhan Ozen"
      - name: Run NPM CI
        run: npm ci
      - name: Build Package
        run: npm run build
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
      #- name: Set NPM registry
      #  run: npm config set registry https://registry.npmjs.org/r-custom-hooks
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
